steps:
- uses: actions/checkout@v2
- uses: actions/setup-node@v1
  with:
    node-version: 'lts/*'
- run: npm install
- run: npm test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
